### ISSUE TITLE
Fungivore Diet (advancement) is impossible

### ISSUE THREAD

**Issue by thelegitdolt** [team-abnormals/irregularity-issues#16]
Fungivore diet adds quark glowshrooms into the list of required mushrooms, but since glowshroom biomes are disabled, you have no way to get glowshrooms, thus making the advanement impossible.

**Comment by thelegitdolt** [comment]
this also applies to danger sight, which is in all_effects and all_potions

**Comment by bageldotjpg** [comment]
fixed indev
